### ISSUE TITLE
Unexpected Class

### ISSUE THREAD

**Issue by remotevase** [remotevase/EasyCMD#1]
class "EasyCMD\c" (EXCEPTION) not found in src\spl\BaseClassLoader at line 144

Something like that. My "ctrl" key isnt working properly, so I couldnt type the code. That's about what it is...

What? That doesn't even exist!

**Comment by Taki21** [comment]
c ??? gonna check probably plugin.yml idk

**Comment by remotevase** [comment]
Naw... Not in there...

**Comment by remotevase** [comment]
Fixed it! It was the C::GREEN and the C:: thing 
I forgot to add
`use pocketmine\utils\TextFormat as C;`
